<?php if ($orders = $this->getOrders()): ?>
    <table>
        <thead>
            <tr>
                <td>Order Number</td>
                <td>Created</td>
                <td>Status</td>
                <td>Items</td>
                <td>Total</td>
                <td>Shipping Method</td>
                <td>Shipping Country</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($orders as $id => $order): ?>
                <tr>
                    <td>
                        <a href="<?php echo $order['url']; ?>" target="_blank"><?php echo $order['number']; ?></a>
                    </td>
                    <td>On <?php echo $order['date']; ?> at <?php echo $order['time']; ?></td>
                    <td><?php echo $order['status']; ?></td>
                    <?php if ($order['items']): ?>
                        <td>
                            <?php foreach ($order['items'] as $id => $item): ?>
                                <div>
                                    <a href="<?php echo $item['url']; ?>" target="_blank"><?php echo $item['quantity']; ?> x <?php echo $item['sku']; ?></a>
                                </div>
                            <?php endforeach; ?>
                        </td>
                    <?php else: ?>
                        <td>None found</td>
                    <?php endif; ?>
                    <td><?php echo $order['total']; ?></td>
                    <?php if (!empty($order['shipping'])): ?>
                        <td><?php echo $order['shipping']; ?></td>
                    <?php else: ?>
                        <td>N/A</td>
                    <?php endif; ?>
                    <?php if (!empty($order['country']) && !empty($order['postcode'])): ?>
                        <td><?php echo $order['country']; ?> (<?php echo $order['postcode']; ?>)</td>
                    <?php else: ?>
                        <td>N/A</td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <?php if ($name = $this->hasCustomerName()): ?>
        <div>No Magento orders found for <?php echo $this->getCustomerName(); ?> (<?php echo $this->getCustomerEmail(); ?>).</div>
    <?php else: ?>
        <div>No Magento orders found for <?php echo $this->getCustomerEmail(); ?>.</div>
    <?php endif; ?>
<?php endif; ?>

<style type="text/css">
    html { font-family:'Helvetica Neue',Arial,sans-serif; }
    body { font-size:13px; margin:0; padding:0; color:#353535; }
    table { border-collapse:collapse; border-spacing:0; width:100%; background-color:#fff; border:1px solid #eaeaea; margin:0; }
    table a { text-decoration:none; color:#353535; }
    table a:hover { text-decoration:underline; color:#353535; }
    thead tr { background-color:#f3f8f9; background-image:linear-gradient(to bottom, #fff 0%, #f3f8f9 100%); }
    thead td { padding:7.5px 15px; border-bottom:1px solid #ccd7da; font-size:12px !important; line-height:1; color:#7d989e; }
    thead, tr, td { vertical-align:middle; }
    table td { border-bottom:1px solid #eaeaea; font-size:13px; }
    table td, table th { padding:8px 15px; vertical-align:middle; }
    *, *:after, *:before { box-sizing:border-box; }
</style>